---
- name: Docker Container creation
  hosts: localhost
  become: true
  tasks:
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
#    - name: Add Docker Repository
#      apt_repository:
#        repo: deb https://download.docker.com/linux/ubuntu bionic stable
#        state: present
    - name: Install Docker Module for Python
      pip: 
        name: docker
    - name: Pull default Docker image
      docker_image:
        name: ubuntu
        source: pull
    - name: Create docker container
      docker_container:
        name: NewContainer
        image: ubuntu
        command: apt install maven
        state: started
    - name: Restart a container
      docker_container:
        name: NewContainer
        image: ubuntu
        state: started
        restart: yes

